# Generated by Django 5.1.4 on 2025-01-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DrugAdminstrations', '0001_initial'),
        ('Frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_drug_prescription',
            name='Booking_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_ip_registration_detials'),
        ),
    ]
