# Generated by Django 5.1.4 on 2025-01-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DrugAdminstrations', '0002_initial'),
        ('Frontoffice', '0001_initial'),
        ('Inventory', '0001_initial'),
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_drug_prescription',
            name='DoctorName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_drug_docname', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='doctor_drug_prescription',
            name='Frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.frequency_master_drug'),
        ),
        migrations.AddField(
            model_name='doctor_drug_prescription',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='doctor_drug_prescription',
            name='ProductCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_drug_med_code', to='Inventory.stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='doctor_drug_prescription',
            name='Specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='ip_drug_request_table',
            name='Booking_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='ip_drug_request_table',
            name='DoctorName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_drug_docname_request', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='ip_drug_request_table',
            name='Frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.frequency_master_drug'),
        ),
        migrations.AddField(
            model_name='ip_drug_request_table',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='ip_drug_request_table',
            name='Prescription_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DrugAdminstrations.doctor_drug_prescription'),
        ),
        migrations.AddField(
            model_name='ip_drug_request_table',
            name='ProductCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_drug_med_code_request', to='Inventory.stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='ip_nurse_drug_completed_administration',
            name='Booking_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='ip_nurse_drug_completed_administration',
            name='DoctorName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_drug_docname_adminis', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='ip_nurse_drug_completed_administration',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='ip_nurse_drug_completed_administration',
            name='Prescription_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DrugAdminstrations.doctor_drug_prescription'),
        ),
        migrations.AddField(
            model_name='ip_nurse_drug_completed_administration',
            name='ProductCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_drug_med_code_adminis', to='Inventory.stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='ip_pharmacy_billing_table_detials',
            name='Doctor_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Pharmacy_Billing_Doctor_Id', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='ip_pharmacy_billing_table_detials',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='ip_pharmacy_billing_table_detials',
            name='Patient_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Pharmacy_Billing_Patient_Id', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='ip_pharmacy_billing_payments',
            name='Billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_billing_payments', to='DrugAdminstrations.ip_pharmacy_billing_table_detials'),
        ),
        migrations.AddField(
            model_name='ip_billingitem',
            name='Billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_billing_items', to='DrugAdminstrations.ip_pharmacy_billing_table_detials'),
        ),
        migrations.AddField(
            model_name='nurse_drug_prescription',
            name='Booking_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='nurse_drug_prescription',
            name='Frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.frequency_master_drug'),
        ),
        migrations.AddField(
            model_name='nurse_drug_prescription',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='nurse_drug_prescription',
            name='ProductCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nurse_drug_med_code', to='Inventory.stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='op_pharmacy_billing_table_detials',
            name='Doctor_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OP_Pharmacy_Billing_Doctor_Id', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='op_pharmacy_billing_table_detials',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='op_pharmacy_billing_table_detials',
            name='Patient_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OP_Pharmacy_Billing_Patient_Id', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='op_pharmacy_billing_payments',
            name='Billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to='DrugAdminstrations.op_pharmacy_billing_table_detials'),
        ),
        migrations.AddField(
            model_name='op_billingitem',
            name='Billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OP_billing_items', to='DrugAdminstrations.op_pharmacy_billing_table_detials'),
        ),
        migrations.AddField(
            model_name='op_pharmacy_walkin_billing_table_detials',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='op_walkin_billingitem',
            name='Billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OP_Walkin_billing_items', to='DrugAdminstrations.op_pharmacy_walkin_billing_table_detials'),
        ),
        migrations.AddField(
            model_name='op_walkin_pharmacy_billing_payments',
            name='Billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments_Walkin', to='DrugAdminstrations.op_pharmacy_walkin_billing_table_detials'),
        ),
    ]
