# Generated by Django 5.1.4 on 2025-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept_Wise_Lenin_min_max_Details',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Prev_Minimum_count', models.IntegerField()),
                ('Curr_Minimum_count', models.IntegerField()),
                ('Prev_Maximum_count', models.IntegerField()),
                ('Curr_Maximum_count', models.IntegerField()),
                ('Status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Dept_Wise_Lenin_min_max_Details',
            },
        ),
        migrations.CreateModel(
            name='Lenin_Catg_Master_Details',
            fields=[
                ('catgId', models.IntegerField(primary_key=True, serialize=False)),
                ('LeninCategory', models.CharField(max_length=30)),
                ('Status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Lenin_Catg_Master_Details',
            },
        ),
        migrations.CreateModel(
            name='Lenin_Stock_Details',
            fields=[
                ('StockId', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.CharField(max_length=30)),
                ('Status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Lenin_Stock_Details',
            },
        ),
        migrations.CreateModel(
            name='LeninMaster_Details',
            fields=[
                ('LeninCode', models.IntegerField(primary_key=True, serialize=False)),
                ('LeninType', models.CharField(max_length=30)),
                ('LeninSize', models.CharField(max_length=30)),
                ('Status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LeninMaster_Details',
            },
        ),
    ]
