# Generated by Django 5.1.4 on 2025-01-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Finance', '0001_initial'),
        ('Inventory', '0001_initial'),
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn_table_detials',
            name='Store_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_location_grn', to='Masters.inventory_location_master_detials'),
        ),
        migrations.AddField(
            model_name='grn_product_item_detials',
            name='Grn_Detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_detials', to='Inventory.grn_table_detials'),
        ),
        migrations.AddField(
            model_name='indent_issue_details_table',
            name='Issue_From_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indent_issue_from_location', to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='indent_issue_details_table',
            name='Issue_From_NurseStation_Location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_issue_from_NurseStation_location', to='Masters.nursestationmaster'),
        ),
        migrations.AddField(
            model_name='indent_issue_details_table',
            name='Issue_From_Store_Location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_issue_from_inv_location', to='Masters.inventory_location_master_detials'),
        ),
        migrations.AddField(
            model_name='indent_issue_details_table',
            name='Issue_To_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indent_issue_to_location', to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='indent_issue_details_table',
            name='Issue_To_NurseStation_Location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_issue_to_NurseStation_location', to='Masters.nursestationmaster'),
        ),
        migrations.AddField(
            model_name='indent_issue_details_table',
            name='Issue_To_Store_Location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_issue_to_inv_location', to='Masters.inventory_location_master_detials'),
        ),
        migrations.AddField(
            model_name='indent_issue_items_details_table',
            name='Indent_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Indent_issue_detials', to='Inventory.indent_issue_details_table'),
        ),
        migrations.AddField(
            model_name='indent_raise_details_table',
            name='Raise_From_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indent_raise_from_location', to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='indent_raise_details_table',
            name='Raise_From_NurseStation_Location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_raise_from_NurseStation_location', to='Masters.nursestationmaster'),
        ),
        migrations.AddField(
            model_name='indent_raise_details_table',
            name='Raise_From_Store_Location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_raise_from_inv_location', to='Masters.inventory_location_master_detials'),
        ),
        migrations.AddField(
            model_name='indent_raise_details_table',
            name='Raise_To_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indent_raise_to_location', to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='indent_raise_details_table',
            name='Raise_To_NurseStation_Location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_raise_to_NurseStation_location', to='Masters.nursestationmaster'),
        ),
        migrations.AddField(
            model_name='indent_raise_details_table',
            name='Raise_To_Store_Location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_raise_to_inv_location', to='Masters.inventory_location_master_detials'),
        ),
        migrations.AddField(
            model_name='indent_issue_details_table',
            name='Indent_raise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_raise_details_issue', to='Inventory.indent_raise_details_table'),
        ),
        migrations.AddField(
            model_name='indent_raise_items_details_table',
            name='Indent_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Indent_raise_detials', to='Inventory.indent_raise_details_table'),
        ),
        migrations.AddField(
            model_name='indent_issue_items_details_table',
            name='Indent_Raise_Item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Indent_raise_detials_issue', to='Inventory.indent_raise_items_details_table'),
        ),
        migrations.AddField(
            model_name='indent_receive_details_table',
            name='Indent_issue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indent_issue_details_receive', to='Inventory.indent_issue_details_table'),
        ),
        migrations.AddField(
            model_name='indent_receive_items_details_table',
            name='Indent_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Indent_receive_detials', to='Inventory.indent_receive_details_table'),
        ),
        migrations.AddField(
            model_name='indent_receive_items_details_table',
            name='Indent_issue_Item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Indent_issue_detials_receive', to='Inventory.indent_issue_items_details_table'),
        ),
        migrations.AddField(
            model_name='location_items_minimum_maximum_detailes',
            name='NurseStation_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Minimum_Maximum_store_location_INS', to='Masters.nursestationmaster'),
        ),
        migrations.AddField(
            model_name='location_items_minimum_maximum_detailes',
            name='Store_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Minimum_Maximum_location_INS', to='Masters.inventory_location_master_detials'),
        ),
        migrations.AddField(
            model_name='old_grn_stock_detials',
            name='Grn_Detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Old_grn_stock_detials', to='Inventory.grn_product_item_detials'),
        ),
        migrations.AddField(
            model_name='old_grn_stock_detials',
            name='NurseStation_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Old_Nurse_store_location_stock', to='Masters.nursestationmaster'),
        ),
        migrations.AddField(
            model_name='old_grn_stock_detials',
            name='Store_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Old_store_location_stock', to='Masters.inventory_location_master_detials'),
        ),
        migrations.AddField(
            model_name='product_category_product_details',
            name='LedgerGroupName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Category_GroupName', to='Finance.finance_groupmaster_detailes'),
        ),
        migrations.AddField(
            model_name='product_category_product_details',
            name='Product_fields',
            field=models.ManyToManyField(related_name='product_category_product_fields', to='Inventory.product_field_details'),
        ),
        migrations.AddField(
            model_name='product_master_all_category_details',
            name='CompanyName',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductMaster_CompanyName', to='Masters.companyname_mfg_master_details'),
        ),
        migrations.AddField(
            model_name='product_master_all_category_details',
            name='GenericName',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductMaster_GenericName', to='Masters.genericname_master_details'),
        ),
        migrations.AddField(
            model_name='product_master_all_category_details',
            name='PackType',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_master_PackType', to='Masters.pack_type_master_details'),
        ),
        migrations.AddField(
            model_name='product_master_all_category_details',
            name='ProductCategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductMaster_Product_Category', to='Inventory.product_category_product_details'),
        ),
        migrations.AddField(
            model_name='product_master_all_category_details',
            name='ProductGroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_master_ProductGroup', to='Masters.product_group_master_details'),
        ),
        migrations.AddField(
            model_name='product_master_all_category_details',
            name='ProductType',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_master_ProductType', to='Masters.producttype_master_details'),
        ),
        migrations.AddField(
            model_name='location_items_minimum_maximum_detailes',
            name='Product_Detailes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Minimum_Maximum_items_INS', to='Inventory.product_master_all_category_details'),
        ),
        migrations.AddField(
            model_name='indent_raise_items_details_table',
            name='Product_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Indent_raise_product_detials', to='Inventory.product_master_all_category_details'),
        ),
        migrations.AddField(
            model_name='indent_issue_items_details_table',
            name='Product_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Indent_raise_product_detials_issue', to='Inventory.product_master_all_category_details'),
        ),
        migrations.AddField(
            model_name='grn_product_item_detials',
            name='Foc_Product_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Foc_Product_grn_items', to='Inventory.product_master_all_category_details'),
        ),
        migrations.AddField(
            model_name='grn_product_item_detials',
            name='Product_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_grn_items', to='Inventory.product_master_all_category_details'),
        ),
        migrations.AddField(
            model_name='product_master_all_category_details',
            name='DrugSegment',
            field=models.ManyToManyField(related_name='Product_Master_Drug_Segment', to='Inventory.productmaster_drug_segment_details'),
        ),
        migrations.AddField(
            model_name='purchase_order_details',
            name='Billing_Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_BillAddress', to='Masters.clinic_detials'),
        ),
        migrations.AddField(
            model_name='purchase_order_details',
            name='Billing_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_BillLocation', to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='purchase_order_details',
            name='Shipping_Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_ShippAddress', to='Masters.clinic_detials'),
        ),
        migrations.AddField(
            model_name='purchase_order_details',
            name='Shipping_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_ShippLocation', to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='grn_table_detials',
            name='Purchase_order_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grn_purchase_order_detials', to='Inventory.purchase_order_details'),
        ),
        migrations.AddField(
            model_name='purchase_order_item_details',
            name='PurchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemTable_PO_Number', to='Inventory.purchase_order_details'),
        ),
        migrations.AddField(
            model_name='purchase_return_details_table',
            name='Store_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_Return_store_location_grn', to='Masters.inventory_location_master_detials'),
        ),
        migrations.AddField(
            model_name='purchase_return_items_details_table',
            name='GRN_Detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_Return_GRN_Table_Detials', to='Inventory.grn_table_detials'),
        ),
        migrations.AddField(
            model_name='purchase_return_items_details_table',
            name='GRN_Item_Detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_Return_GRN_Product_Item_Detials', to='Inventory.grn_product_item_detials'),
        ),
        migrations.AddField(
            model_name='purchase_return_items_details_table',
            name='Purchase_Return_Details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_Return_Details_For_Items', to='Inventory.purchase_return_details_table'),
        ),
        migrations.AddField(
            model_name='serialnumber_stock_maintance_table_detials',
            name='NurseStation_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SerialNumber_NurseStation_store_location_stock', to='Masters.nursestationmaster'),
        ),
        migrations.AddField(
            model_name='serialnumber_stock_maintance_table_detials',
            name='Product_Detailes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SerialNumber_Product_stock_items', to='Inventory.product_master_all_category_details'),
        ),
        migrations.AddField(
            model_name='serialnumber_stock_maintance_table_detials',
            name='Store_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SerialNumber_store_location_stock', to='Masters.inventory_location_master_detials'),
        ),
        migrations.AddField(
            model_name='indent_receive_items_details_table',
            name='Damaged_serialNo',
            field=models.ManyToManyField(related_name='indent_receive_serial_numbers_Damaged', to='Inventory.serialnumber_stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='indent_receive_items_details_table',
            name='Pending_serialNo',
            field=models.ManyToManyField(related_name='indent_receive_serial_numbers_Pending', to='Inventory.serialnumber_stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='indent_receive_items_details_table',
            name='Received_serialNo',
            field=models.ManyToManyField(related_name='indent_receive_serial_numbers_Received', to='Inventory.serialnumber_stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='indent_issue_items_details_table',
            name='serialNo',
            field=models.ManyToManyField(related_name='indent_issued_serial_numbers', to='Inventory.serialnumber_stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='stock_maintance_table_detials',
            name='NurseStation_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NurseStation_store_location_stock', to='Masters.nursestationmaster'),
        ),
        migrations.AddField(
            model_name='stock_maintance_table_detials',
            name='Product_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_stock_items', to='Inventory.product_master_all_category_details'),
        ),
        migrations.AddField(
            model_name='stock_maintance_table_detials',
            name='Store_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_location_stock', to='Masters.inventory_location_master_detials'),
        ),
        migrations.AddField(
            model_name='serialnumber_stock_maintance_table_detials',
            name='Stock_Table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SerialNumber_Stock_Table', to='Inventory.stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='purchase_return_items_details_table',
            name='Stock_Detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_Return_Stock_Detials', to='Inventory.stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='indent_issue_items_details_table',
            name='stock_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Indent_issue_items_stock_details', to='Inventory.stock_maintance_table_detials'),
        ),
        migrations.AddField(
            model_name='subcategory_detailes',
            name='ProductCategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductCategoryId', to='Inventory.product_category_product_details'),
        ),
        migrations.AddField(
            model_name='product_master_all_category_details',
            name='SubCategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductMaster_SubCategory', to='Inventory.subcategory_detailes'),
        ),
        migrations.AddField(
            model_name='supplier_bank_details',
            name='Supplier_Detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bank_Supp_name', to='Inventory.supplier_master_details'),
        ),
        migrations.AddField(
            model_name='purchase_return_details_table',
            name='Supplier_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_Return_Grn_supplier_detials', to='Inventory.supplier_master_details'),
        ),
        migrations.AddField(
            model_name='purchase_order_details',
            name='Supplier_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_SupplierID', to='Inventory.supplier_master_details'),
        ),
        migrations.AddField(
            model_name='grn_table_detials',
            name='Supplier_Detials',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grn_supplier_detials', to='Inventory.supplier_master_details'),
        ),
        migrations.AddField(
            model_name='supplier_pay_detials',
            name='Grn_Detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_pay_grn_detials', to='Inventory.grn_table_detials'),
        ),
        migrations.AddField(
            model_name='supplier_pay_by_date',
            name='Supplier_pay_detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_pay_by_Supplier_pay_detials', to='Inventory.supplier_pay_detials'),
        ),
        migrations.AddField(
            model_name='supplier_product_details',
            name='Product_Detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product_master_all_category_details'),
        ),
        migrations.AddField(
            model_name='supplier_product_details',
            name='Supplier_Detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_detials_for_product', to='Inventory.supplier_master_details'),
        ),
        migrations.AddField(
            model_name='supplier_product_amount_details',
            name='Supplier_detials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_Product_Details_Amount', to='Inventory.supplier_product_details'),
        ),
        migrations.AddField(
            model_name='purchase_order_item_details',
            name='PO_Item_Detailes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_Item_ID', to='Inventory.supplier_product_details'),
        ),
        migrations.AddField(
            model_name='product_master_all_category_details',
            name='VolumeType',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_master_Volume_Type', to='Inventory.unitofmeasurement'),
        ),
    ]
