# Generated by Django 5.1.4 on 2025-01-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Patient_Entry_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('Patient_ServiesType', models.CharField(max_length=40)),
                ('PreAuthDate', models.DateField(default=None, null=True)),
                ('PreAuthAmount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('DischargeDate', models.DateField(default=None, null=True)),
                ('FinalBillAmount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('RaisedAmount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('ApprovedAmount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('CourierDate', models.DateField(default=None, null=True)),
                ('SettlementDateCount', models.IntegerField(default=None, null=True)),
                ('Papersstatus', models.CharField(default='PENDING', max_length=80)),
                ('SubmittedBy', models.CharField(default=None, max_length=100, null=True)),
                ('CompletedBy', models.CharField(default=None, max_length=100, null=True)),
                ('RejectedBy', models.CharField(default=None, max_length=100, null=True)),
                ('TdsPercentage', models.FloatField(blank=True, null=True)),
                ('TdsAmount', models.FloatField(blank=True, null=True)),
                ('FinalSettlementAmount', models.FloatField(blank=True, null=True)),
                ('IsCopayment', models.CharField(default=None, max_length=100, null=True)),
                ('CopaymentBillAmount', models.FloatField(blank=True, null=True)),
                ('CopaymentType', models.CharField(default=None, max_length=100, null=True)),
                ('CopaymentTypeValue', models.FloatField(blank=True, null=True)),
                ('CoPaymentFinalAmount', models.FloatField(blank=True, null=True)),
                ('Updated_by', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Patient_Amount_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SettlementDate', models.DateField()),
                ('SettlementAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UTR_Number', models.CharField(max_length=200)),
                ('Created_By', models.CharField(max_length=100)),
                ('Updated_by', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('Client_Entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AmountTableClientDetailes', to='Insurance.client_patient_entry_details')),
            ],
        ),
        migrations.CreateModel(
            name='Insuranse_Patient_Entery_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('Patient_ServiesType', models.CharField(max_length=40)),
                ('PreAuthDate', models.DateField(default=None, null=True)),
                ('PreAuthAmount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('DischargeDate', models.DateField(default=None, null=True)),
                ('FinalBillAmount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('RaisedAmount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('ApprovedAmount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('CourierDate', models.DateField(default=None, null=True)),
                ('SettlementDateCount', models.IntegerField(default=None, null=True)),
                ('Papersstatus', models.CharField(default='PENDING', max_length=80)),
                ('SubmittedBy', models.CharField(default=None, max_length=100, null=True)),
                ('CompletedBy', models.CharField(default=None, max_length=100, null=True)),
                ('RejectedBy', models.CharField(default=None, max_length=100, null=True)),
                ('TdsPercentage', models.FloatField(blank=True, null=True)),
                ('TdsAmount', models.FloatField(blank=True, null=True)),
                ('FinalSettlementAmount', models.FloatField(blank=True, null=True)),
                ('InsuranceType', models.CharField(default=None, max_length=100, null=True)),
                ('PolicyNumber', models.CharField(default=None, max_length=100, null=True)),
                ('IsEmployee', models.CharField(default=None, max_length=100, null=True)),
                ('CompanyName', models.CharField(default=None, max_length=100, null=True)),
                ('Employeeid', models.CharField(default=None, max_length=100, null=True)),
                ('EmployeeDesignation', models.CharField(default=None, max_length=100, null=True)),
                ('IsCopayment', models.CharField(default=None, max_length=100, null=True)),
                ('CopaymentBillAmount', models.FloatField(blank=True, null=True)),
                ('CopaymentType', models.CharField(default=None, max_length=100, null=True)),
                ('CopaymentTypeValue', models.FloatField(blank=True, null=True)),
                ('CoPaymentFinalAmount', models.FloatField(blank=True, null=True)),
                ('Updated_by', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Insuranse_Patient_Amount_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SettlementDate', models.DateField()),
                ('SettlementAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UTR_Number', models.CharField(max_length=200)),
                ('Created_By', models.CharField(max_length=100)),
                ('Updated_by', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('Insurance_Entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AmountTableInsuranceDetailes', to='Insurance.insuranse_patient_entery_details')),
            ],
        ),
    ]
