# Generated by Django 5.1.4 on 2025-01-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Frontoffice', '0001_initial'),
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_request_list',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='appointment_request_list',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_request_list_doctor_name', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='appointment_request_list',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_request_list_specialization', to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='appointment_request_list',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Appointment_title', to='Masters.title_detials'),
        ),
        migrations.AddField(
            model_name='appointment_reschedule_request',
            name='appointmentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.appointment_request_list'),
        ),
        migrations.AddField(
            model_name='appointment_reschedule_request',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_reschedule_list_doctor_name', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='appointment_reschedule_request',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_reschedule_list_specialization', to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='emergencyregister',
            name='PrimaryDoctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emg_register_Doctor', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='emergencyregister',
            name='Speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emg_register_specialities', to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='general_billing_table_detials',
            name='Doctor_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Billing_Doctor_Id', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='general_billing_table_detials',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location_id', to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='general_billing_items_table_detials',
            name='Billing_Invoice_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Table_Billing_Invoice_No', to='Frontoffice.general_billing_table_detials'),
        ),
        migrations.AddField(
            model_name='generalbillingreceipt',
            name='Invoice_NO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_invoice', to='Frontoffice.general_billing_table_detials'),
        ),
        migrations.AddField(
            model_name='ip_billing_add_services',
            name='Location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='ip_billing_queuelist_detials',
            name='Doctor_Ratecard_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Queue_Doctor_Ratecard_Id', to='Masters.doctor_ratecard_master'),
        ),
        migrations.AddField(
            model_name='ip_billing_add_services',
            name='BillingDataList_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.ip_billing_queuelist_detials'),
        ),
        migrations.AddField(
            model_name='ip_billing_table_detials',
            name='Doctor_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Doctor_Id', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='ip_billing_items_table_detials',
            name='Billing_Invoice_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Table_IP_Billing_Invoice_No', to='Frontoffice.ip_billing_table_detials'),
        ),
        migrations.AddField(
            model_name='multiple_payment_table_ip_detials',
            name='Invoice_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Multiple_Payment_IP_Billing_Invoice', to='Frontoffice.ip_billing_table_detials'),
        ),
        migrations.AddField(
            model_name='op_billing_queuelist_detials',
            name='Doctor_Ratecard_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OP_Billing_Doctor_Ratecard_Id', to='Masters.doctor_ratecard_master'),
        ),
        migrations.AddField(
            model_name='opd_flow',
            name='AppointmentDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_previous_doctor_name', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='opd_flow',
            name='Appointment_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.appointment_request_list'),
        ),
        migrations.AddField(
            model_name='opd_flow',
            name='DoctorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_doctor_name', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='opd_flow',
            name='Specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_detials',
            name='DrInchargeAtTimeOfAdmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_room_detials',
            name='RoomId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.room_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='ApptoRegId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.appointment_request_list'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='ClientName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.client_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='CorporateName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_details_CorporateId', to='Masters.corporate_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='DoctorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_DoctorId', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='DonationType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_details_DonationId', to='Masters.donation_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='EmployeeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_EmployeeId', to='Masters.employee_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='InsuranceName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.insurance_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='PrimaryDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_doctor', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='ResheduleDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='ResheduleSpeciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='Specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_speciality', to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_cancel_details',
            name='Registration_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_registration_details', to='Frontoffice.patient_appointment_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_detials',
            name='OP_Registration_Id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_appointment_registration_detials'),
        ),
        migrations.AddField(
            model_name='opd_flow',
            name='Registration_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_appointment_registration_detials'),
        ),
        migrations.AddField(
            model_name='op_to_ip_convertion_table',
            name='Registration_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_appointment_registration_detials'),
        ),
        migrations.AddField(
            model_name='op_billing_queuelist_detials',
            name='Registration_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OP_Billing_QueueList_Registration_Id', to='Frontoffice.patient_appointment_registration_detials'),
        ),
        migrations.AddField(
            model_name='general_billing_table_detials',
            name='Register_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Billing_Patient_Id', to='Frontoffice.patient_appointment_registration_detials'),
        ),
        migrations.AddField(
            model_name='advancemaintaintable',
            name='Register_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advmaintain_Patient_Id', to='Frontoffice.patient_appointment_registration_detials'),
        ),
        migrations.AddField(
            model_name='advanceamounttable',
            name='Register_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advance_Patient_Id', to='Frontoffice.patient_appointment_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_casuality_registration_detials',
            name='ClientName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.client_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_casuality_registration_detials',
            name='DoctorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casuality_appointment_DoctorId', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_casuality_registration_detials',
            name='EmployeeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casuality_appointment_EmployeeId', to='Masters.employee_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_casuality_registration_detials',
            name='Flagging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.flaggcolor_detials'),
        ),
        migrations.AddField(
            model_name='patient_casuality_registration_detials',
            name='InsuranceName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.insurance_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_casuality_registration_detials',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='patient_casuality_registration_detials',
            name='PrimaryDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casuality_appointment_doctor', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_casuality_registration_detials',
            name='Specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casuality_appointment_speciality', to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_room_detials',
            name='Casuality_Registration_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_casuality_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_detials',
            name='Casuality_Registration_Id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_casuality_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_client_insurance_details',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='patient_detials',
            name='BloodGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientId_Bloodgroup', to='Masters.bloodgroup_detials'),
        ),
        migrations.AddField(
            model_name='patient_detials',
            name='Flagging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.flaggcolor_detials'),
        ),
        migrations.AddField(
            model_name='patient_detials',
            name='Religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Orgional_patientId', to='Masters.religion_detials'),
        ),
        migrations.AddField(
            model_name='patient_detials',
            name='Title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientId_Title', to='Masters.title_detials'),
        ),
        migrations.AddField(
            model_name='patient_client_insurance_details',
            name='Patient_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='patient_casuality_registration_detials',
            name='PatientId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casuality_appointment_details', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='patient_appointment_registration_detials',
            name='PatientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_details', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='opd_flow',
            name='Patient_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='op_to_ip_convertion_table',
            name='Patient_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='ip_billing_table_detials',
            name='Patient_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Patient_Id', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='general_billing_table_detials',
            name='Patient_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Billing_Patient_Id', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='duplicates_patients',
            name='Duplicates_patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Duplicates_patientId', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='duplicates_patients',
            name='Orgional_patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orgional_patientId', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='advancemaintaintable',
            name='Patient_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advmaintain_Patient_Id', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='advanceamounttable',
            name='Patient_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advance_Patient_Id', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='patient_diagnosis_registration_detials',
            name='ClientName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.client_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_diagnosis_registration_detials',
            name='DoctorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Diagnosis_appointment_DoctorId', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_diagnosis_registration_detials',
            name='EmployeeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Diagnosis_appointment_EmployeeId', to='Masters.employee_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_diagnosis_registration_detials',
            name='Flagging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.flaggcolor_detials'),
        ),
        migrations.AddField(
            model_name='patient_diagnosis_registration_detials',
            name='InsuranceName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.insurance_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_diagnosis_registration_detials',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='patient_diagnosis_registration_detials',
            name='PatientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Diagnosis_appointment_details', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='patient_diagnosis_registration_detials',
            name='PrimaryDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Diagnosis_appointment_doctor', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_diagnosis_registration_detials',
            name='Specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Diagnosis_appointment_speciality', to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_detials',
            name='Diagnosis_Registration_Id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_diagnosis_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='ClientName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.client_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='CorporateName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emergency_patient_details_CorporateId', to='Masters.corporate_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='DoctorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emergency_appointment_DoctorId', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='DonationType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emergency_patient_details_DonationId', to='Masters.donation_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='EmployeeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emergency_appointment_EmployeeId', to='Masters.employee_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='Flagging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.flaggcolor_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='InsuranceName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.insurance_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='PatientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='PrimaryDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Primary_doctor_Emergency_details', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_emergency_registration_detials',
            name='Specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_room_detials',
            name='Emergency_Registration_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_emergency_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_detials',
            name='Emergency_Registration_Id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_emergency_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='ClientName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.client_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='CorporateName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IP_patient_details_CorporateId', to='Masters.corporate_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='DoctorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IP_appointment_DoctorId', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='DonationType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IP_patient_details_DonationId', to='Masters.donation_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='EmployeeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IP_appointment_EmployeeId', to='Masters.employee_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='Flagging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.flaggcolor_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='InsuranceName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.insurance_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='PatientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='PrimaryDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Primary_doctor_ip_details', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_ip_registration_detials',
            name='Specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_room_detials',
            name='IP_Registration_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_detials',
            name='IP_Registration_Id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='ip_billing_table_detials',
            name='Register_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Patient_Id', to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='ip_billing_queuelist_detials',
            name='Registration_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Registration_Id', to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='handover_detials_ip',
            name='RegistrationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Handover_Ip_register', to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='advance_collection_ip',
            name='RegistrationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_laboratory_registration_detials',
            name='ClientName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.client_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_laboratory_registration_detials',
            name='DoctorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Laboratory_appointment_DoctorId', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_laboratory_registration_detials',
            name='EmployeeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Laboratory_appointment_EmployeeId', to='Masters.employee_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_laboratory_registration_detials',
            name='Flagging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.flaggcolor_detials'),
        ),
        migrations.AddField(
            model_name='patient_laboratory_registration_detials',
            name='InsuranceName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.insurance_master_detials'),
        ),
        migrations.AddField(
            model_name='patient_laboratory_registration_detials',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.location_detials'),
        ),
        migrations.AddField(
            model_name='patient_laboratory_registration_detials',
            name='PatientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Laboratory_appointment_details', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='patient_laboratory_registration_detials',
            name='PrimaryDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_appointment_doctor', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_laboratory_registration_detials',
            name='Specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_appointment_speciality', to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='patient_admission_detials',
            name='Laboratory_Registration_Id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_laboratory_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_referral_detials',
            name='Casuality_Register_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_casuality_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_referral_detials',
            name='Diagnosis_Register_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_diagnosis_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_referral_detials',
            name='Emergency_Register_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_emergency_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_referral_detials',
            name='IP_Register_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_referral_detials',
            name='Laboratory_Register_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_laboratory_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_referral_detials',
            name='OP_Register_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.patient_appointment_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_referral_detials',
            name='ReferredBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_doctorname', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_registration_reshedule_details',
            name='AppointmentDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_reschedule_previous_doctor', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_registration_reshedule_details',
            name='Registration_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reshedule_registration_details', to='Frontoffice.patient_appointment_registration_detials'),
        ),
        migrations.AddField(
            model_name='patient_registration_reshedule_details',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_reschedule_list_doctor_name', to='Masters.doctor_personal_form_detials'),
        ),
        migrations.AddField(
            model_name='patient_registration_reshedule_details',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_reschedule_list_specialization', to='Masters.speciality_detials'),
        ),
        migrations.AddField(
            model_name='patient_visit_detials',
            name='PatientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Visit_patient_detials', to='Frontoffice.patient_detials'),
        ),
        migrations.AddField(
            model_name='ip_billing_table_detials',
            name='Visit_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Visit_Id', to='Frontoffice.patient_visit_detials'),
        ),
        migrations.AddField(
            model_name='general_billing_table_detials',
            name='Visit_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Billing_Visit_Id', to='Frontoffice.patient_visit_detials'),
        ),
        migrations.AddField(
            model_name='advancemaintaintable',
            name='Visit_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advmaintain_Visit_Id', to='Frontoffice.patient_visit_detials'),
        ),
        migrations.AddField(
            model_name='advanceamounttable',
            name='Visit_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advance_Visit_Id', to='Frontoffice.patient_visit_detials'),
        ),
        migrations.AddField(
            model_name='service_procedure_request_ip',
            name='Procedure_ratecard',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Procedure_charges_ip', to='Masters.procedure_master_details'),
        ),
        migrations.AddField(
            model_name='service_procedure_request_ip',
            name='RegistrationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_Procedure_request_Ip', to='Frontoffice.patient_ip_registration_detials'),
        ),
        migrations.AddField(
            model_name='service_procedure_request_ip',
            name='RoomId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RoomId_service_procedure', to='Masters.room_master_detials'),
        ),
        migrations.AddField(
            model_name='service_procedure_request_ip',
            name='Service_ratecard',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Service_charges_ip', to='Masters.service_master_details'),
        ),
    ]
