# Generated by Django 5.1.4 on 2025-01-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontoffice', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abha_collectin_data',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abha_collectin_data',
            name='pincode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
